{% set name = "snowflake-snowpark-python" %}
{% set version = "0.9.0" %}
{% set sha256 = "ebf65ab300b691189bc2972f5a81ab635dc91b8cf87c57a1c4f1eb09c409039d" %}
# rebuild trigger 1

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snowflakedb/snowpark-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py!=38 or win32 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps -vvv 

requirements:
  host:
    - python
    - pip
    - setuptools >=40.6.0
    - wheel
  run:
    - python
    - cloudpickle >=1.6.0,<=2.0.0
    - snowflake-connector-python>=2.7.11
    - typing-extensions >=4.1.0
  run_constrained:
    - pandas >1,<1.4

test:
  requires:
    - pip
  imports:
    - snowflake.snowpark
  commands:
    - pip check

about:
  home: https://github.com/snowflakedb/snowpark-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Snowflake Snowpark Python API
  description: |
      The Snowpark library provides intuitive APIs for querying and
      processing data in a data pipeline. Using this library, you can
      build applications that process data in Snowflake without having
      to move data to the system where your application code runs.
  dev_url: https://github.com/snowflakedb/snowpark-python
  doc_url: https://github.com/snowflakedb/snowpark-python/blob/main/README.md
