{% set name = "snowflake-snowpark-python" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: git@github.com:snowflakedb/snowpark-python.git
  git_rev: v{{ version }}
  git_hash: c97ea5f2c56049c19c93cc63512f6ce1bec94a19

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - wheel
  host:
    - python 3.8
    - pip
  run:
    - python 3.8
    - cloudpickle >=1.6.0
    - snowflake-connector-python
    - setuptools >34.0.0
    - typing-extensions >=4.1.0
  run_constrained:
    - pandas >1,<1.4

test:
  imports:
    - snowflake
    - snowflake.snowpark

about:
  home: https://github.com/snowflakedb/snowpark-python
  summary: Snowpark Python
