{% set name = "snowflake-snowpark-python" %}
{% set version = "1.5.0" %}
{% set sha256 = "e9203942c8e4cba1067e6ea05aa35f52c19fd9d510386a5c0af859dafe05b35c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snowflakedb/snowpark-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<38 or win32 or s390x or py>=310 and not test_py310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv 
  script_env:
    - SNOWFLAKE_IS_PYTHON_RUNTIME_TEST=1  # [test_py310]

requirements:
  host:
    - python
    - pip
    - setuptools >=40.6.0
    - wheel
  run:
    - python
    - cloudpickle >=1.6.0,<=2.0.0
    - snowflake-connector-python >=2.7.12,<4.0.0a0
    - typing-extensions >=4.1.0,<5.0.0a0

test:
  requires:
    - pip
  imports:
    - snowflake.snowpark
  commands:
    - pip check

about:
  home: https://github.com/snowflakedb/snowpark-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Snowflake Snowpark Python API
  description: |
      The Snowpark library provides intuitive APIs for querying and
      processing data in a data pipeline. Using this library, you can
      build applications that process data in Snowflake without having
      to move data to the system where your application code runs.
  dev_url: https://github.com/snowflakedb/snowpark-python
  doc_url: https://github.com/snowflakedb/snowpark-python/blob/main/README.md
