{% set name = "snowflake-snowpark-python" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: git@github.com:snowflakedb/snowpark-python.git
  git_rev: v{{ version }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  host:
    - python
    - pip
    - setuptools >=40.6.0
    - wheel
  run:
    - python 3.8
    - cloudpickle >=1.6.0
    # Requires snowflake-connector-python >=2.7.4 but Anaconda hasn't it yet
    - snowflake-connector-python
    - typing-extensions >=4.1.0
  run_constrained:
    - pandas >1,<1.4

test:
  imports:
    - snowflake
    - snowflake.snowpark

about:
  home: https://github.com/snowflakedb/snowpark-python
  license: Apache-2.0
  license_family: Apache
  summary: Snowpark Python
  dev_url: https://github.com/snowflakedb/snowpark-python
  doc_url: https://github.com/snowflakedb/snowpark-python/blob/main/README.md
