{% set name = "snowflake-snowpark-python" %}
{% set version = "1.5.1" %}
{% set sha256 = "de4be59b246de323967772fcd4276baa8023f54f90413aff88dfb6b60b674d25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snowflakedb/snowpark-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<38 or s390x or py>=311]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv


requirements:
  host:
    - python
    - pip
    - setuptools >=40.6.0
    - wheel
  run:
    - python >=3.8,<3.10
    - cloudpickle >=1.6.0,<=2.0.0
    - snowflake-connector-python >=2.7.12,<4.0.0
    - typing-extensions >=4.1.0,<5.0.0

test:
  requires:
    - pip
  imports:
    - snowflake.snowpark
    - snowflake.snowpark._internal
  commands:
    - pip check

about:
  home: https://github.com/snowflakedb/snowpark-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Snowflake Snowpark Python API
  description: |
      The Snowpark library provides intuitive APIs for querying and
      processing data in a data pipeline. Using this library, you can
      build applications that process data in Snowflake without having
      to move data to the system where your application code runs.
  dev_url: https://github.com/snowflakedb/snowpark-python
  doc_url: https://github.com/snowflakedb/snowpark-python/blob/main/README.md

extra:
  recipe-maintainers:
    - sfc-gh-yixie
    - sfc-gh-achandrasekaran
    - sfc-gh-mkeller