{% set name = "snowflake-snowpark-python" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/snowflakedb/snowpark-python.git
  git_rev: v{{ version }}

build:
  number: 0
  noarch: python
  skip: true  # [win32 or s390x or py<36]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - wheel
    - git
  host:
    - python 3.8
    - pip
  run:
    - python 3.8
    - cloudpickle >=1.6.0,<=2.0.0
    - snowflake-connector-python
    - setuptools >34.0.0
    - typing-extensions >=4.1.0
  run_constrained:
    - pandas >1,<1.4

test:
  imports:
    - snowflake
    - snowflake.snowpark

about:
  home: https://github.com/snowflakedb/snowpark-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Snowflake Snowpark Python API
  description: |
      The Snowpark library provides intuitive APIs for querying and
      processing data in a data pipeline. Using this library, you can
      build applications that process data in Snowflake without having
      to move data to the system where your application code runs.
  doc_url: https://docs.snowflake.com/en/LIMITEDACCESS/snowpark-python.html
  dev_url: https://github.com/snowflakedb/snowpark-python
